### PR TITLE
Change instance vars for their respective value

### PR DESCRIPTION
**Pull request by MrOutis**
Assets in production are precompiled, so they don't know anything about those instance variables.
This is a quick fix to show the data, however this should be refactored.

### CODE REVIEW

**Comment by ricalanis** [comment]
You are right. After this, we just make sure that we run:
`RAILS_ENV=production rake assets:precompile`
Can you confirm if this is a needed step?

**Comment by MrOutis** [comment]
When running in development mode, Rails will automagically prepare your assets.

On production, you'll need to run `rake assets:precompile`, this will create `public/assets`, and likely you'll be running an nginx instance serving this directory.

Read the following for more info: http://guides.rubyonrails.org/asset_pipeline.html

**Comment by ricalanis** [comment]
Awesome. Will add this to deploy guide.

**Comment by MrOutis** [comment]
Test it, tho, take this PR as a suggestion instead of a bullet proof solution.

**Pull request merged**
